### ISSUE TITLE
loss_ellipse not decreasing

### ISSUE THREAD

**Issue by Caspeerrr** [wdoppenberg/ellipse-rcnn#2]
I've tried testing my own dataset with fairly easy separable ellipses, but of the losses only the loss_ellipse is not decreasing and stays constant. Is there an additional prepossessing step to generate the conic_matrices or do you have any other idea for a fix?

**Comment by Liuk2072** [comment]
I also encountered this situation, did you solve it later?

**Comment by Liuk2072** [comment]
> I've tried testing my own dataset with fairly easy separable ellipses, but of the losses only the loss_ellipse is not decreasing and stays constant. Is there an additional prepossessing step to generate the conic_matrices or do you have any other idea for a fix?

I also encountered this situation, did you solve it later?

**Comment by Caspeerrr** [comment]
> 

No, unfortunately I haven't been able to solve it yet.

**Comment by Caspeerrr** [comment]
No, unfortunately I haven't been able to solve it yet.

**Comment by shree-exofield** [comment]
I am also facing the same problem, does anyone able to solve this ? for me the model is not converging at all.
