### ISSUE TITLE
Can you make a guide/tutorial ? 

### ISSUE THREAD

**Issue by mcafier** [wdoppenberg/ellipse-rcnn#3]
Hi, thank you for your implementation !

I'm fairly new to deep learning, and to be honest I find it difficult to use your work on my own dataset.
Would you consider to elaborate a bit more  on your Readme file ? To explain for example how to install, how to train it on a new dataset (maybe what should be modified in the model depending on the daataset) and how to test it ? 

I know I'm asking for a lot but this would be so helpful, and I think many this would result in many people using your github and citing you. 

Thank you !  :-)

**Comment by wdoppenberg** [comment]
Hi @MotsPassant ! 

Sure, however I don't necessarily have a lot of free time to spend on this project. Although I am committed to making this a more usable library. As you might've seen I've overhauled some of core conic transformation functions recently. My current focus is on aligning my implementation with the reference [paper](https://arxiv.org/abs/2001.11584). 

In the meantime I'll think about writing a more detailed documentation file.

**Comment by mcafier** [comment]
Nice ! 

Well I'm really looking forward to your update !
